# https://docs.pytest.org/en/stable/how-to/monkeypatch.html

import pytest
from fastapi.testclient import TestClient
from fastapi_mqtt_endpoint import app
from fastapi_mqtt_endpoint import fast_mqtt
from fastapi_mqtt_endpoint import _lifespan

client = TestClient(app)

""" 2025-12-09: generated by Copilot """
def test_read_root():
    response = client.get("/")
    assert response.status_code == 200
    data = response.json()
    assert data["FastAPI"] == "Hello World!"
    # assert response.text == "FastAPI: Hello World!"

""" 2025-12-09: generated by Copilot """
def test_publish_message_success_mocking(monkeypatch):
    published = {}

    # Mock the fast_mqtt.publish method
    def mock_publish(topic, message, **kwargs):
        published['topic'] = topic
        published['message'] = message

    # Patch the publish method in the app's module
    monkeypatch.setattr(fast_mqtt, "publish", mock_publish)

    topic = "test/topic"
    message = "hello world"
    response = client.post(
        "/publish",
        params={"topic": topic, "message": message}
    )
    assert response.status_code == 200
    data = response.json()
    assert data["result"] == "Message published"
    assert data["topic"] == topic
    assert data["message"] == message
    assert published["topic"] == topic
    assert published["message"] == message


""" 2025-12-09: generated by Copilot """
def test_publish_message_missing_params():
    # Missing both topic and message
    response = client.post("/publish")
    assert response.status_code == 422

    # Missing topic
    response = client.post("/publish", params={"message": "msg"})
    assert response.status_code == 422

    # Missing message
    response = client.post("/publish", params={"topic": "topic"})
    assert response.status_code == 422


"""
def test_mqtt_connect_handler(monkeypatch):
    # Mock the MQTT client and its subscribe method
    mock_client = MagicMock()
    mock_client.subscribe = MagicMock()
    
    # Get the connect handler
    connect_handler = fast_mqtt._on_connect
    
    # Call the connect handler
    connect_handler(mock_client, flags=0, rc=0, properties=None)
    
    # Assert that subscribe was called with the correct topic
    mock_client.subscribe.assert_called_once_with("fastapi-mqtt/test")
"""


"""
def test_publish_message_success(monkeypatch):
    # published = {}

    # # Mock the fast_mqtt.publish method
    # def mock_publish(topic, message, **kwargs):
    #     published['topic'] = topic
    #     published['message'] = message

    # # Patch the publish method in the app's module
    # monkeypatch.setattr(fast_mqtt, "publish", mock_publish)

    topic = "test/topic"
    message = "hello world"
    response = client.post(
        "/publish",
        params={"topic": topic, "message": message}
    )
    assert response.status_code == 200
    data = response.json()
    assert data["result"] == "Message published"
    assert data["topic"] == topic
    assert data["message"] == message

    # assert published["topic"] == topic
    # assert published["message"] == message
"""